export const REQUEST_ACTIONS = Object.freeze({
    REQUEST_START: "REQUEST_START",
    REQUEST_SUCCESS: "REQUEST_SUCCESS",
    REQUEST_ERROR: "REQUEST_ERROR"
})

export const USER_ACTIONS = Object.freeze({
  ADD_USER: "ADD_USER",
  REMOVE_USER: "REMOVE_USER",
  MODIFY_USER: "MODIFY_USER",
  GET_USERS: "GET_USERS"
});

export const SAGA_USER_ACTIONS = Object.freeze({
  ADD_USER_ASYNC: "ADD_USER_ASYNC",
  REMOVE_USER_ASYNC: "REMOVE_USER_ASYNC",
  MODIFY_USER_ASYNC: "MODIFY_USER_ASYNC",
  GET_USERS_ASYNC: "GET_USERS_ASYNC"
});
