export const REQUEST_ACTIONS = Object.freeze({
  REQUEST_START: "REQUEST_START",
  REQUEST_SUCCESS: "REQUEST_SUCCESS",
  REQUEST_ERROR: "REQUEST_ERROR",
});

export const USER_ACTIONS = Object.freeze({
  ADD_USER: "ADD_USER",
  REMOVE_USER: "REMOVE_USER",
  MODIFY_USER: "MODIFY_USER",
  GET_USERS: "GET_USERS",
  ADD_ACCOUNT: "ADD_USER_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
});

export const SAGA_USER_ACTIONS = Object.freeze({
  ADD_USER_ASYNC: "ADD_USER_ASYNC",
  REMOVE_USER_ASYNC: "REMOVE_USER_ASYNC",
  MODIFY_USER_ASYNC: "MODIFY_USER_ASYNC",
  GET_CURRENT_USER_ASYNC: "GET_CURRENT_USER_ASYNC",
  GET_USERS_ASYNC: "GET_USERS_ASYNC",
  ADD_ACCOUNT_ASYNC: "ADD_ACCOUNT_ASYNC",
  DELETE_ACCOUNT_ASYNC: "DELETE_ACCOUNT_ASYNC",
  CHANGE_PASSWORD_ASYNC: "CHANGE_PASSWORD_ASYNC",
});

export const GROUP_ACTIONS = Object.freeze({
  ADD_GROUP: "ADD_GROUP",
  REMOVE_GROUP: "REMOVE_GROUP",
  MODIFY_GROUP: "MODIFY_GROUP",
  GET_GROUPS: "GET_GROUPS",
  ADD_ACCOUNT: "ADD_ACCOUNT",
  ADD_USER: "ADD_GROUP_USER",
  REMOVE_USER: "REMOVE_USER_GROUP",
});

export const CURRENT_GROUP_ACTIONS = Object.freeze({
  LOAD_CURRENT_GROUP: "LOAD_CURRENT_GROUPS",
  UNLOAD_CURRENT_GROUP: "UNLOAD_CURRENT_GROUPS",
  ADD_TO_CURRENT_GROUP_ACCOUNT: "ADD_TO_CURRENT_GROUP_ACCOUNT",
  ADD_CURRENT_GROUP_ACCOUNT: "ADD_CURRENT_GROUP_ACCOUNT",
  REMOVE_CURRENT_GROUP_ACCOUNT: "REMOVE_CURRENT_GROUP_ACCOUNT",
  ADD_CURRENT_GROUP_USER: "ADD_CURRENT_GROUP_USER",
  REMOVE_CURRENT_GROUP_USER: "REMOVE_CURRENT_GROUP_USER",
});

export const SAGA_GROUP_ACTIONS = Object.freeze({
  ADD_GROUP_ASYNC: "ADD_GROUP_ASYNC",
  REMOVE_GROUP_ASYNC: "REMOVE_GROUP_ASYNC",
  MODIFY_GROUP_ASYNC: "MODIFY_GROUP_ASYNC",
  GET_GROUP_ASYNC: "GET_GROUP_ASYNC",
  GET_GROUPS_ASYNC: "GET_GROUPS_ASYNC",
  ADD_ACCOUNT_ASYNC: "ADD_GROUP_ACCOUNT_ASYNC",
  REMOVE_ACCOUNT_ASYNC: "REMOVE_ACCOUNT_ASYNC",
  ADD_USER_ASYNC: "ADD_USER_GROUP_ASYNC",
  REMOVE_USER_ASYNC: "REMOVE_USER_GROUP_ASYNC",
});

export const CURRENT_USER_ACTIONS = Object.freeze({
  SET_CURRENT_USER_DATA: "SET_CURRENT_USER_DATA",
  SET_CURRENT_USER_TOKEN: "SET_CURRENT_USER_TOKEN",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  UNSET_CURRENT_USER: "UNSET_CURRENT_USER",
  ADD_TO_CURRENT_USER_ACCOUNT: "ADD_TO_CURRENT_USER_ACCOUNT",
  CURRENT_USER_ADD_ACCOUNT: "CURRENT_USER_ADD_ACCOUNT",
  CURRENT_USER_DELETE_ACCOUNT: "CURRENT_USER_DELETE_ACCOUNT",
});

export const ACTIVITY_ACTIONS = Object.freeze({
  GET_ACTIVITIES: "GET_ACTIVITIES",
  ADD_ACTIVITY: "ADD_ACTIVITY",
  DELETE_ACTIVITY: "DELETE_ACTIVITY",
  EDIT_ACTIVITY: "EDIT_ACTIVITY",
});

export const SAGA_ACTIVITY_ACTIONS = Object.freeze({
  GET_ACTIVITIES_ASYNC: "GET_ACTIVITIES_ASYNC",
  ADD_ACTIVITY_ASYNC: "ADD_ACTIVITY_ASYNC",
  DELETE_ACTIVITY_ASYNC: "DELETE_ACTIVITY_ASYNC",
  EDIT_ACTIVITY_ASYNC: "EDIT_ACTIVITY_ASYNC",
});

export const POLLS_ACTIONS = Object.freeze({
  GET_POLLS: "GET_POLLS",
  ADD_POLL: "ADD_POLL",
  DELETE_POLL: "DELETE_POLL",
  EDIT_POLL: "EDIT_POLL",
});

export const SAGA_POLLS_ACTIONS = Object.freeze({
  GET_POLLS_ASYNC: "GET_POLLS_ASYNC",
  ADD_POLL_ASYNC: "ADD_POLL_ASYNC",
  DELETE_POLL_ASYNC: "DELETE_POLL_ASYNC",
  EDIT_POLL_ASYNC: "EDIT_POLL_ASYNC",
  VOTE_POLL_ASYNC: "VOTE_POLL_ASYNC",
});

export const URL = "http://localhost:3001";
